name: Lint and Generate

on:
  pull_request:
  push:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        env:
          GOBIN: /home/runner/go/bin
        with:
          go-version: v1.19.x
          cache: true
      - name: setup
        run: |
          go install github.com/projectdiscovery/yamldoc-go/cmd/docgen/dstdocgen@latest
      - name: lint
        run: go run mage.go lint
      - name: markdown
        run: go run mage.go markdown >> $GITHUB_STEP_SUMMARY
